import turtle

jake = turtle.Turtle()
jake.shape("turtle")
jake.color("Red")

def main():
    jake.begin_fill()
    jake.color("Red")
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(80)
    jake.end_fill()

    jake.begin_fill()
    jake.color("Orange")
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(80)
    jake.end_fill()

    jake.begin_fill()
    jake.color("Yellow")
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(80)
    jake.end_fill()

    jake.begin_fill()
    jake.color("Green")
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(80)
    jake.end_fill()

    jake.begin_fill()
    jake.color("Blue")
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(80)
    jake.end_fill()

    jake.begin_fill()
    jake.color("Purple")
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(90)
    jake.forward(80)
    jake.right(80)
    jake.end_fill()


for lap in range(0,36):
    main()
    
main()
